/**
 * A published editor edit of a runtime-generated PA connector must survive the
 * next world load. HighwayMap guards those overrides so an old one, captured
 * against a differently fitted lot, cannot land a lane across the stall rows —
 * but that guard used to reject deliberate fresh edits too, because reshaping a
 * connector is exactly "the terminus no longer sits on the generated curve".
 * The `base` stamp the editor now saves is what separates the two cases.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { HighwayMap } from '../../../../js/map.js';

const map = new HighwayMap(null, { addLighting: false });
test.after(() => map.dispose());

const ROUTE_ID = 'tatsumi_pa_exit';
const route = map.routes.get(ROUTE_ID);

test('runtime-generated routes expose the polyline they were generated from', () => {
  assert.ok(route, `${ROUTE_ID} is generated by the map`);
  assert.equal(route.synthetic, true);
  // The stamp is the geometry BEFORE any published override replaced the
  // route's points, so it is deliberately independent of route.points.
  assert.ok(Array.isArray(route.generatedPoints) && route.generatedPoints.length >= 2);
  assert.ok(route.generatedPoints.every((point) => point.length === 3 && point.every(Number.isFinite)));
  assert.equal(map._matchesGeneratedBase(route, route.generatedPoints), true);
  assert.equal(map.routes.get('wangan_0').generatedPoints, null, 'production routes carry no stamp');
});

test('a stamped edit that moves the on-deck terminus is kept, unstamped is not', () => {
  const base = route.generatedPoints.map((point) => [...point]);
  // The reshape the guard used to eat: drop the first control points and pull
  // the new terminus well off the generated curve.
  const edited = base.slice(3).map((point) => [...point]);
  edited[0] = [edited[0][0] + 9, edited[0][1] + 3, edited[0][2] - 11];

  assert.equal(map._syntheticOverrideIsStale(ROUTE_ID, edited, base), false,
    'an edit stamped with the current generated polyline is authoritative');
  assert.equal(map._syntheticOverrideIsStale(ROUTE_ID, edited, null), true,
    'without a stamp the conservative geometric heuristic still applies');
});

test('a stamp from a differently fitted lot is rejected', () => {
  const shifted = route.generatedPoints.map((point) => [point[0] + 40, point[1], point[2] + 40]);
  const edited = route.generatedPoints.map((point) => [...point]);
  edited[0] = [edited[0][0] + 9, edited[0][1] + 3, edited[0][2] - 11];
  assert.equal(map._syntheticOverrideIsStale(ROUTE_ID, edited, shifted), true);
  // A stamp of the wrong length is a rebuilt route, not a rounding difference.
  assert.equal(map._syntheticOverrideIsStale(ROUTE_ID, edited, route.generatedPoints.slice(1)), true);
});

test('the stamp tolerates the override file rounding but not real geometry moves', () => {
  const rounded = route.generatedPoints.map((point) => point.map(
    (value) => Math.round((value + Number.EPSILON) * 100000) / 100000,
  ));
  assert.equal(map._matchesGeneratedBase(route, rounded), true);
  const nudged = route.generatedPoints.map((point) => [...point]);
  nudged[2] = [nudged[2][0] + 0.5, nudged[2][1], nudged[2][2]];
  assert.equal(map._matchesGeneratedBase(route, nudged), false);
});
